# Generated by Django 4.2.7 on 2023-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KosdaqSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basDt', models.DateField()),
                ('idxNm', models.CharField(max_length=50)),
                ('clpr', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KospiSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basDt', models.DateField()),
                ('idxNm', models.CharField(max_length=50)),
                ('clpr', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KrxSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basDt', models.DateField()),
                ('idxNm', models.CharField(max_length=50)),
                ('clpr', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basDt', models.DateField()),
                ('idxNm', models.CharField(max_length=50)),
                ('clpr', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
